Add fileWithOutputDirectoryContext for dynamic output path resolution
takahirom/roborazzi pull request #172
Opened 2023-09-26 01:28 UTC by takahirom

close https://github.com/takahirom/roborazzi/issues/171

2023-09-26 01:46 UTC, takahirom commented
Now, custom_file.png is saved to build/outputs/roborazzi/custom_file.png instead of just custom_file.png. This change has occurred, so we need to exercise caution. Many people rely on the path used by captureRoboImage, so this change could have implications.

2023-09-26 14:18 UTC, timothyfroehlich requested changes
I just realized there's this line in the [Readme](https://github.com/takahirom/roborazzi#roborazzirule-optional): `Provide context such as RoborazziOptions and outputDirectoryPath etc for captureRoboImage().`. 

So it's worth pointing out that this is essentially a bug fix to make the behavior of `captureRobo...` match the documentation.

2023-09-27 01:17 UTC, takahirom commented on include-build/roborazzi-core/src/commonJvmMain/kotlin/com/github/takahirom/roborazzi/fileWithOutputDirectoryContext.kt
> +    val prefixRemovedFilePath = filePathAbsolutePath.removePrefix("$outputDirectoryAbsolutePath/")
Thanks. Adding a parameter to captureRoboImage() could lead to frequent usage, making it challenging to modify the API later. Additionally, users would be required to specify the property every time. A gradle.properties flag might be a more flexible option.

2023-09-27 18:54 UTC, timothyfroehlich commented
Looks good so far! Can you make sure you document the new property in the Readme or somewhere? Thanks!

2023-09-28 00:48 UTC, takahirom commented on include-build/roborazzi-core/src/commonJvmMain/kotlin/com/github/takahirom/roborazzi/RoborazziOptions.kt
> +      "roborazzi.captureRoboImage.filePathStrategy",
This property doesn't affect comparison images like hoge_compare.png. Therefore, I believe roborazzi.record.filePathStrategy would be a more appropriate name.

2023-09-28 00:50 UTC, takahirom commented on include-build/roborazzi-core/src/commonJvmMain/kotlin/com/github/takahirom/roborazzi/RoborazziOptions.kt
> +      "roborazzi.captureRoboImage.filePathStrategy",
And we may provide the filePathStrategy in RoborazziContext someday.

2023-09-28 00:51 UTC, takahirom commented on include-build/roborazzi-core/src/commonJvmMain/kotlin/com/github/takahirom/roborazzi/RoborazziOptions.kt
> +      "roborazzi.record.filePathStrategy",
The property name has been changed.
https://github.com/takahirom/roborazzi/pull/172#discussion_r1339384610

2023-09-28 01:39 UTC, takahirom commented
@timothyfroehlich 
Thank you for your review! I've uploaded the document. Could you please take a look?
https://github.com/takahirom/roborazzi/blob/bd771a41f3d82ec788366291ca3fef4da313b18a/README.md#roborazzi-gradleproperties-options

2023-09-30 04:21 UTC, merged